Exile_AdminGetItemList = compile preprocessfile "UG_AM\functions\Exile_AdminGetItemList.sqf";
Exile_AdminGetItemDetails = compile preprocessfile "UG_AM\functions\Exile_AdminGetItemDetails.sqf";
Exile_AdminGetVicClassname = compile preprocessfile "UG_AM\functions\Exile_AdminGetVicClassname.sqf";
Exile_AdminGetVehiclePicture = compile preprocessfile "UG_AM\functions\Exile_AdminGetVehiclePicture.sqf";
Exile_AdminGetBackpackPicture = compile preprocessfile "UG_AM\functions\Exile_AdminGetBackpackPicture.sqf";
Exile_AdminGetHeadgearPicture = compile preprocessfile "UG_AM\functions\Exile_AdminGetHeadgearPicture.sqf";
Exile_AdminSpawnonSelf = compile preprocessfile "UG_AM\functions\Exile_AdminSpawnonSelf.sqf";
Exile_AdminSpawnCreateHolder = compile preprocessfile "UG_AM\functions\Exile_AdminSpawnCreateHolder.sqf";
_nil = execVM "UG_AM\functions\Exile_AdminGetItemInfo.sqf";
Exile_AdminShowSpawnDialog = compile preprocessfile "UG_AM\functions\Exile_AdminShowSpawnDialog.sqf";
Exile_AdminSpawnOnLoad = compile preprocessfile "UG_AM\SpawnOnload.sqf";
diag_log "FUNCTIONS LOADED";